#ifndef VERSION_INFO_H
#define VERSION_INFO_H

#define VERSION_MAJOR 1
#define VERSION_MINOR 240
#define VERSION_PATCH 2

#define VERSION_INFO_FREETEXT "sup-2728"

#define VERSION_CANOPEN_MAJOR   1
#define VERSION_CANOPEN_MINOR   5
#define VERSION_CANOPEN_PATCH   0

#endif /* VERSION_INFO_H */